# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-04 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newassetapprovalzone',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='制造商'),
        ),
    ]
