# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-04 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asset', '0004_auto_20170704_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newassetapprovalzone',
            name='sn',
            field=models.CharField(max_length=128, verbose_name='SN号'),
        ),
    ]
