# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-04 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asset', '0006_auto_20170704_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='ram',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
