# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-04 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asset', '0007_ram_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='asset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Asset.Asset'),
        ),
    ]
