# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-04 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asset', '0008_auto_20170704_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ram',
            name='slot',
            field=models.CharField(max_length=128, verbose_name='插槽'),
        ),
    ]
