# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-06 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asset', '0009_auto_20170704_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nic',
            name='mac_address',
            field=models.CharField(max_length=128, unique=True, verbose_name='MAC地址'),
        ),
    ]
