# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-07 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asset', '0011_auto_20170706_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='token_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
